title: excruzme
email: joyce@excruz.me
description: >- # this means to ignore newlines until "baseurl:"
  excruzme - pages.
github_username:  excruzme

# Build settings
theme: minima
plugins:
  - jekyll-feed